sonar.projectKey=2024tm93593_devops-assignment-1
sonar.projectName=2024tm93593_devops-assignment-1
sonar.projectVersion=3.2.4
sonar.organization=2024tm93593
sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/tests/**,**/*.pyc
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
