apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-green-state
  namespace: default
data:
  active-color: "blue"
  previous-color: "none"
  active-image: "chetan56881/aceest-fitness-app:latest"
  last-switched: "never"
