apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-app
  namespace: a-site
  labels:
    app: aceest-fitness-app
    variant: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness-app
      variant: a
  template:
    metadata:
      labels:
        app: aceest-fitness-app
        variant: a
    spec:
      automountServiceAccountToken: false
      containers:
        - name: aceest-fitness-app
          image: chetan56881/aceest-fitness-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
