apiVersion: v1
kind: ConfigMap
metadata:
  name: aceest-nginx-config
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 5000;

        location / {
          mirror /shadow;
          mirror_request_body on;
          proxy_pass http://aceest-fitness-app.prod.svc.cluster.local:5000;
        }

        location /shadow {
          internal;
          proxy_pass http://aceest-fitness-app.shadow.svc.cluster.local:5000;
        }
      }
    }
