apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-app
  namespace: shadow
spec:
  type: ClusterIP
  selector:
    app: aceest-fitness-app
    track: shadow
  ports:
    - port: 5000
      targetPort: 5000
